Resources:
  AppsyncapiGraphQlDsusersTable:
      Type: "AWS::AppSync::DataSource"
      Properties:
        ApiId: !GetAtt AppsyncapiGraphQlApi.ApiId
        Name: UsersTable
        Type: AMAZON_DYNAMODB
        ServiceRoleArn: { Fn::GetAtt: [AppsyncDynamoDBRole, Arn] }
        DynamoDBConfig:
          AwsRegion: ${self:custom.region}
          TableName: !Ref Users
  