Resources:
  AppsyncapiGraphQlDsusersTable:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppsyncapiGraphQlApi.ApiId
      Name: UsersTable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: { Fn::GetAtt: [AppsyncDynamoDBRole, Arn] }
      DynamoDBConfig:
        AwsRegion: ${self:custom.region}
        TableName: !Ref Users
  AppsyncapiGraphQlDsgetImageUploadUrlFunction:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppsyncapiGraphQlApi.ApiId
      Name: ImageUpload
      Type: AWS_LAMBDA
      ServiceRoleArn: { Fn::GetAtt: [AppsyncLambdaInvokeRole, Arn] }
      LambdaConfig:
        LambdaFunctionArn: { Fn::GetAtt: [GetImageUploadUrlLambdaFunction, Arn] }
  AppsyncapiGraphQlDstweetFunction:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppsyncapiGraphQlApi.ApiId
      Name: Tweet
      Type: AWS_LAMBDA
      ServiceRoleArn: { Fn::GetAtt: [AppsyncLambdaInvokeRole, Arn] }
      LambdaConfig:
        LambdaFunctionArn: { Fn::GetAtt: [TweetLambdaFunction, Arn] }
  