Resources:
  AppsyncDynamoDBRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: appsync-backend-app-dynamodb-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "AppSyncBackendRolePolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:GetItem"
                    - "dynamodb:Scan"
                    - "dynamodb:PutItem"
                    - "dynamodb:UpdateItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:BatchGetItem"
                  Resource:
                    - { Fn::GetAtt: [ Users, Arn ] }
                    - { Fn::GetAtt: [ Tweets, Arn ] }
                    - { Fn::GetAtt: [ Timelines, Arn ] }
                    - !Sub ${Tweets.Arn}/*
  AppsyncLambdaInvokeRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: appsync-backend-app-lambdainvoke-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "AppSyncBackendLambdaInvokeRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "lambda:invokeFunction"
                Resource:
                  - !GetAtt GetImageUploadUrlLambdaFunction.Arn    
                  - !GetAtt TweetLambdaFunction.Arn