name: appsyncapi
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref AppsyncBackendUserPool
mappingTemplatesLocation: mapping-templates
datasources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: { Ref: Users }
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: { Ref: Timelines }
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: { Ref: Tweets }
  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: { Ref: Likes }
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweet
  - type: AWS_LAMBDA
    name: retweetFunction
    config:
      functionName: retweet
  - type: AWS_LAMBDA
    name: unretweetFunction
    config:
      functionName: unretweet
mappingTemplates:
#QUERIES
  - type: Query
    field: getMyProfile
    dataSource: usersTable
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: getTweets
    dataSource: tweetsTable
  - type: Query
    field: getLikes
    dataSource: likesTable
  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable
#MUTATIONS
  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false
  - type: Mutation
    field: retweet
    dataSource: retweetFunction
    request: false
    response: false
  - type: Mutation
    field: unretweet
    dataSource: unretweetFunction
    request: false
    response: false
  - type: Mutation
    field: like
    dataSource: likesTable
  - type: Mutation
    field: unlike
    dataSource: likesTable
#NESTED FIELDS
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: TimelinePage
    field: tweets
    dataSource: tweetsTable
  - type: Tweet
    field: liked
    dataSource: likesTable
  - type: MyProfile
    field: tweets
    dataSource: tweetsTable
  - type: Retweet
    field: profile
    dataSource: usersTable
    request: Tweet.Profile.request.vtl
    response: Tweet.Profile.response.vtl
  - type: Retweet
    field: retweetOf
    dataSource: tweetsTable
substitutions:
  TweetsTable: !Ref Tweets
  LikesTable: !Ref Likes
  UsersTable: !Ref Users